version: "3"

services:
  myapp:
    container_name: pharmacy-management-app
    image: node:18-alpine
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "8080:8080"
    networks:
      - net
    # ports:
    #   - "8080:8080"
    command: sh -c "npm install && node index.js"

networks:
  net:
    driver: bridge
    name: net
